"""initial schema: structure, user

Revision ID: 3032398bfa21
Revises: 
Create Date: 2026-08-29 15:06:57.907263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3032398bfa21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tribe_id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.String(), nullable=False),
    sa.Column('struct_key', sa.String(), nullable=False),
    sa.Column('class', sa.String(), nullable=False),
    sa.Column('kind_hint', sa.String(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('has_item_count', sa.Boolean(), nullable=False),
    sa.Column('ammo', sa.Float(), nullable=True),
    sa.Column('range', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('powered', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tribe_id', 'map_id', 'struct_key', name='uq_structure_tribe_map_key')
    )
    op.create_index(op.f('ix_structure_tribe_id'), 'structure', ['tribe_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_structure_tribe_id'), table_name='structure')
    op.drop_table('structure')
    # ### end Alembic commands ###
