"""add auth and ark schema

Revision ID: 93868d516e83
Revises: 3032398bfa21
Create Date: 2026-08-30 17:43:25.887745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93868d516e83'
down_revision: Union[str, Sequence[str], None] = '3032398bfa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_status',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('activation_key_origin',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('activation_key_status',
    sa.Column('is_terminal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('admin_role',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('admin_status',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('api_key_status',
    sa.Column('is_terminal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('cluster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False, comment='cpu_id, motherboard, mac, ip ...'),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_map',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('group_role',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('invite_status',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('log_event_type',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('person',
    sa.Column('platform_id', sa.Text(), nullable=False, comment='НАБЛЮДАЕМЫЙ игрок (не наш аккаунт!)'),
    sa.Column('platform_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_table('species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_path', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_path')
    )
    op.create_table('structure_class',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False, comment='turret/generator/foundation/wall/...'),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('default_decay_seconds', sa.Integer(), nullable=True, comment='эталонное время жизни класса без рефреша'),
    sa.Column('is_turret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_powered_type', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='argon2id + перец'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='подписка; двигается ключом'),
    sa.Column('status_code', sa.Text(), server_default='active', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_code'], ['account_status.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_expires_at', 'account', ['expires_at'], unique=False)
    op.create_index('uq_account_login_active', 'account', ['login'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('admin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='argon2id + перец'),
    sa.Column('role_code', sa.Text(), server_default='admin', nullable=False),
    sa.Column('status_code', sa.Text(), server_default='active', nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True, comment='NULL у первого (CLI)'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['role_code'], ['admin_role.code'], ),
    sa.ForeignKeyConstraint(['status_code'], ['admin_status.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('server',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('map_code', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['map_code'], ['game_map.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activation_key',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='SHA-256, НЕ argon2'),
    sa.Column('duration', postgresql.INTERVAL(), nullable=False),
    sa.Column('origin_code', sa.Text(), server_default='purchase', nullable=False),
    sa.Column('status_code', sa.Text(), server_default='issued', nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_account_id', sa.UUID(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True, comment='кто купил = идентификатор продажи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_code'], ['activation_key_origin.code'], ),
    sa.ForeignKeyConstraint(['redeemed_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['status_code'], ['activation_key_status.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_activation_key_redeemed_by_account_id'), 'activation_key', ['redeemed_by_account_id'], unique=False)
    op.create_index(op.f('ix_activation_key_tg_user_id'), 'activation_key', ['tg_user_id'], unique=False)
    op.create_table('api_key',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False, comment='SHA-256; плейнтекст 1 раз'),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('last4', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Text(), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['status_code'], ['api_key_status.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_key_account_id'), 'api_key', ['account_id'], unique=False)
    op.create_table('fingerprint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('composite_hash', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fingerprint_account_id'), 'fingerprint', ['account_id'], unique=False)
    op.create_index(op.f('ix_fingerprint_composite_hash'), 'fingerprint', ['composite_hash'], unique=False)
    op.create_table('sharing_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tribe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('ark_tribe_id', sa.BigInteger(), nullable=True, comment='если есть сейв; иначе по имени'),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='аудит: когда воркер тронул строку'),
    sa.Column('last_updated_by_account_id', sa.UUID(), nullable=True, comment='АВТОР последнего апдейта'),
    sa.ForeignKeyConstraint(['last_updated_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tribe_last_updated_by_account_id', 'tribe', ['last_updated_by_account_id'], unique=False)
    op.create_index('uq_tribe_server_name', 'tribe', ['server_id', 'name'], unique=True)
    op.create_table('api_key_scope',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.PrimaryKeyConstraint('api_key_id', 'scope')
    )
    op.create_table('ark_structure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('object_hash', sa.Text(), nullable=False, comment='hash(class + КВАНТ. x/y/z до snap-грида)'),
    sa.Column('class_code', sa.Text(), nullable=False),
    sa.Column('tribe_id', sa.UUID(), nullable=True, comment='NULL допустим'),
    sa.Column('x', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('y', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('z', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('health', sa.REAL(), nullable=True),
    sa.Column('decay_remaining_seconds', sa.Integer(), nullable=True, comment='ФАКТИЧЕСКОЕ оставшееся время, полученное из игры; НЕ вычисляется'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False, comment='первое наблюдение'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False, comment='последнее наблюдение'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='аудит: когда воркер тронул строку'),
    sa.Column('last_updated_by_account_id', sa.UUID(), nullable=True, comment='АВТОР последнего апдейта'),
    sa.ForeignKeyConstraint(['class_code'], ['structure_class.code'], ),
    sa.ForeignKeyConstraint(['last_updated_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ark_structure_decay_remaining_seconds', 'ark_structure', ['decay_remaining_seconds'], unique=False)
    op.create_index('ix_ark_structure_last_updated_by_account_id', 'ark_structure', ['last_updated_by_account_id'], unique=False)
    op.create_index('ix_ark_structure_tribe_id', 'ark_structure', ['tribe_id'], unique=False)
    op.create_index('uq_ark_structure_server_object_hash', 'ark_structure', ['server_id', 'object_hash'], unique=True)
    op.create_table('fingerprint_component',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_id', sa.UUID(), nullable=False),
    sa.Column('component_type_id', sa.UUID(), nullable=False),
    sa.Column('value_hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['component_type_id'], ['component_type.id'], ),
    sa.ForeignKeyConstraint(['fingerprint_id'], ['fingerprint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint_id', 'component_type_id', name='uq_fingerprint_component_pair')
    )
    op.create_table('group_invite_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='SHA-256; плейнтекст 1 раз'),
    sa.Column('created_by_account_id', sa.UUID(), nullable=False),
    sa.Column('grants_role_code', sa.Text(), server_default='member', nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True, comment='NULL = безлимит; 1 = одноразовый'),
    sa.Column('uses_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status_code', sa.Text(), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['grants_role_code'], ['group_role.code'], ),
    sa.ForeignKeyConstraint(['group_id'], ['sharing_group.id'], ),
    sa.ForeignKeyConstraint(['status_code'], ['invite_status.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_group_invite_token_group_id'), 'group_invite_token', ['group_id'], unique=False)
    op.create_table('group_member',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.Text(), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['sharing_group.id'], ),
    sa.ForeignKeyConstraint(['role_code'], ['group_role.code'], ),
    sa.PrimaryKeyConstraint('group_id', 'account_id')
    )
    op.create_index('ix_group_member_account_id', 'group_member', ['account_id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('tribe_id', sa.UUID(), nullable=True),
    sa.Column('character_name', sa.Text(), nullable=True, comment='ник — меняется, НЕ ключ'),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('x', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('y', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('z', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='когда наблюдался в игре'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='аудит: когда воркер тронул строку'),
    sa.Column('last_updated_by_account_id', sa.UUID(), nullable=True, comment='АВТОР последнего апдейта'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['person.platform_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_account_id'), 'player', ['account_id'], unique=False)
    op.create_index(op.f('ix_player_last_updated_by_account_id'), 'player', ['last_updated_by_account_id'], unique=False)
    op.create_index(op.f('ix_player_tribe_id'), 'player', ['tribe_id'], unique=False)
    op.create_index('uq_player_server_platform', 'player', ['server_id', 'platform_id'], unique=True)
    op.create_table('tamed_dino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('tribe_id', sa.UUID(), nullable=True, comment='NULL = анклейм. В object_hash НЕ идёт'),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=True, comment='male/female'),
    sa.Column('color_0', sa.SmallInteger(), nullable=True, comment='регионы 0..5 — стабильны у взрослого'),
    sa.Column('color_1', sa.SmallInteger(), nullable=True),
    sa.Column('color_2', sa.SmallInteger(), nullable=True),
    sa.Column('color_3', sa.SmallInteger(), nullable=True),
    sa.Column('color_4', sa.SmallInteger(), nullable=True),
    sa.Column('color_5', sa.SmallInteger(), nullable=True),
    sa.Column('object_hash', sa.Text(), nullable=True, comment='hash(species + gender + color_0..5). СИГНАЛ, не unique'),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True, comment='растёт — не в ключ'),
    sa.Column('x', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('y', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('z', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='когда наблюдался в игре'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='аудит: когда воркер тронул строку'),
    sa.Column('last_updated_by_account_id', sa.UUID(), nullable=True, comment='АВТОР последнего апдейта'),
    sa.ForeignKeyConstraint(['last_updated_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tamed_dino_last_updated_by_account_id'), 'tamed_dino', ['last_updated_by_account_id'], unique=False)
    op.create_index(op.f('ix_tamed_dino_object_hash'), 'tamed_dino', ['object_hash'], unique=False)
    op.create_index(op.f('ix_tamed_dino_server_id'), 'tamed_dino', ['server_id'], unique=False)
    op.create_index(op.f('ix_tamed_dino_species_id'), 'tamed_dino', ['species_id'], unique=False)
    op.create_index(op.f('ix_tamed_dino_tribe_id'), 'tamed_dino', ['tribe_id'], unique=False)
    op.create_table('tribe_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_day', sa.Integer(), nullable=True, comment='ARK Day N'),
    sa.Column('event_type_code', sa.Text(), nullable=False),
    sa.Column('actor_tribe_id', sa.UUID(), nullable=True),
    sa.Column('target_tribe_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.Text(), nullable=True),
    sa.Column('target_name', sa.Text(), nullable=True),
    sa.Column('species_id', sa.UUID(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='СЫРАЯ строка — нераспарсенное не теряется'),
    sa.Column('reported_by_account_id', sa.UUID(), nullable=True, comment='АВТОР (кто прислал лог)'),
    sa.ForeignKeyConstraint(['actor_tribe_id'], ['tribe.id'], ),
    sa.ForeignKeyConstraint(['event_type_code'], ['log_event_type.code'], ),
    sa.ForeignKeyConstraint(['reported_by_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['target_tribe_id'], ['tribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tribe_log_actor_tribe_id'), 'tribe_log', ['actor_tribe_id'], unique=False)
    op.create_index(op.f('ix_tribe_log_event_type_code'), 'tribe_log', ['event_type_code'], unique=False)
    op.create_index(op.f('ix_tribe_log_reported_by_account_id'), 'tribe_log', ['reported_by_account_id'], unique=False)
    op.create_index('ix_tribe_log_server_occurred_at', 'tribe_log', ['server_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_tribe_log_target_tribe_id'), 'tribe_log', ['target_tribe_id'], unique=False)
    op.create_table('ark_structure_generator',
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('is_powered', sa.Boolean(), nullable=True),
    sa.Column('fuel_amount', sa.REAL(), nullable=True),
    sa.Column('power_range', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['ark_structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('structure_id')
    )
    op.create_table('ark_structure_turret',
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('ammo_count', sa.Integer(), nullable=True),
    sa.Column('range', sa.REAL(), nullable=True, comment='радиус — карта покрытия'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True, comment='players/dinos/all/survivors'),
    sa.ForeignKeyConstraint(['structure_id'], ['ark_structure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('structure_id')
    )
    # ### end Alembic commands ###

    _seed_lookups()


# Конечные списки значений (models/auth_lookups.py, models/ark_lookups.py) —
# без них ни один FK на *_code не пройдёт (admin.role_code -> admin_role.code
# и т.д.), а самому приложению эти строки заводить не положено: это
# перечисление состояний домена, а не пользовательские данные.
def _seed_lookups() -> None:
    op.bulk_insert(
        sa.table('admin_role', sa.column('code', sa.Text()), sa.column('label', sa.Text())),
        [
            {'code': 'superadmin', 'label': 'Суперадминистратор'},
            {'code': 'admin', 'label': 'Администратор'},
            {'code': 'support', 'label': 'Поддержка'},
            {'code': 'developer', 'label': 'Разработчик'},
        ],
    )
    op.bulk_insert(
        sa.table('admin_status', sa.column('code', sa.Text()), sa.column('label', sa.Text())),
        [
            {'code': 'active', 'label': 'Активен'},
            {'code': 'disabled', 'label': 'Отключён'},
            {'code': 'locked', 'label': 'Заблокирован'},
        ],
    )
    op.bulk_insert(
        sa.table('account_status', sa.column('code', sa.Text()), sa.column('label', sa.Text())),
        [
            {'code': 'active', 'label': 'Активен'},
            {'code': 'suspended', 'label': 'Приостановлен'},
        ],
    )
    op.bulk_insert(
        sa.table('activation_key_origin', sa.column('code', sa.Text()), sa.column('label', sa.Text())),
        [
            {'code': 'purchase', 'label': 'Покупка'},
            {'code': 'invite', 'label': 'Приглашение'},
            {'code': 'gift', 'label': 'Подарок'},
        ],
    )
    op.bulk_insert(
        sa.table(
            'activation_key_status',
            sa.column('code', sa.Text()),
            sa.column('label', sa.Text()),
            sa.column('is_terminal', sa.Boolean()),
        ),
        [
            {'code': 'issued', 'label': 'Выдан', 'is_terminal': False},
            {'code': 'redeemed', 'label': 'Погашен', 'is_terminal': True},
        ],
    )
    op.bulk_insert(
        sa.table(
            'api_key_status',
            sa.column('code', sa.Text()),
            sa.column('label', sa.Text()),
            sa.column('is_terminal', sa.Boolean()),
        ),
        [
            {'code': 'active', 'label': 'Активен', 'is_terminal': False},
            {'code': 'revoked', 'label': 'Отозван', 'is_terminal': True},
        ],
    )
    op.bulk_insert(
        sa.table('group_role', sa.column('code', sa.Text()), sa.column('label', sa.Text())),
        [
            {'code': 'owner', 'label': 'Владелец'},
            {'code': 'member', 'label': 'Участник'},
        ],
    )
    op.bulk_insert(
        sa.table('invite_status', sa.column('code', sa.Text()), sa.column('label', sa.Text())),
        [
            {'code': 'active', 'label': 'Активно'},
            {'code': 'revoked', 'label': 'Отозвано'},
            {'code': 'expired', 'label': 'Истекло'},
        ],
    )
    op.bulk_insert(
        sa.table('log_event_type', sa.column('code', sa.Text()), sa.column('label', sa.Text())),
        [
            {'code': 'tame', 'label': 'Приручение'},
            {'code': 'kill', 'label': 'Убийство'},
            {'code': 'structure_destroyed', 'label': 'Постройка разрушена'},
            {'code': 'member_joined', 'label': 'Участник вступил'},
            {'code': 'member_left', 'label': 'Участник покинул'},
            {'code': 'claimed', 'label': 'Заклеймлено'},
            {'code': 'demolished', 'label': 'Снесено'},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ark_structure_turret')
    op.drop_table('ark_structure_generator')
    op.drop_index(op.f('ix_tribe_log_target_tribe_id'), table_name='tribe_log')
    op.drop_index('ix_tribe_log_server_occurred_at', table_name='tribe_log')
    op.drop_index(op.f('ix_tribe_log_reported_by_account_id'), table_name='tribe_log')
    op.drop_index(op.f('ix_tribe_log_event_type_code'), table_name='tribe_log')
    op.drop_index(op.f('ix_tribe_log_actor_tribe_id'), table_name='tribe_log')
    op.drop_table('tribe_log')
    op.drop_index(op.f('ix_tamed_dino_tribe_id'), table_name='tamed_dino')
    op.drop_index(op.f('ix_tamed_dino_species_id'), table_name='tamed_dino')
    op.drop_index(op.f('ix_tamed_dino_server_id'), table_name='tamed_dino')
    op.drop_index(op.f('ix_tamed_dino_object_hash'), table_name='tamed_dino')
    op.drop_index(op.f('ix_tamed_dino_last_updated_by_account_id'), table_name='tamed_dino')
    op.drop_table('tamed_dino')
    op.drop_index('uq_player_server_platform', table_name='player')
    op.drop_index(op.f('ix_player_tribe_id'), table_name='player')
    op.drop_index(op.f('ix_player_last_updated_by_account_id'), table_name='player')
    op.drop_index(op.f('ix_player_account_id'), table_name='player')
    op.drop_table('player')
    op.drop_index('ix_group_member_account_id', table_name='group_member')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_group_invite_token_group_id'), table_name='group_invite_token')
    op.drop_table('group_invite_token')
    op.drop_table('fingerprint_component')
    op.drop_index('uq_ark_structure_server_object_hash', table_name='ark_structure')
    op.drop_index('ix_ark_structure_tribe_id', table_name='ark_structure')
    op.drop_index('ix_ark_structure_last_updated_by_account_id', table_name='ark_structure')
    op.drop_index('ix_ark_structure_decay_remaining_seconds', table_name='ark_structure')
    op.drop_table('ark_structure')
    op.drop_table('api_key_scope')
    op.drop_index('uq_tribe_server_name', table_name='tribe')
    op.drop_index('ix_tribe_last_updated_by_account_id', table_name='tribe')
    op.drop_table('tribe')
    op.drop_table('sharing_group')
    op.drop_index(op.f('ix_fingerprint_composite_hash'), table_name='fingerprint')
    op.drop_index(op.f('ix_fingerprint_account_id'), table_name='fingerprint')
    op.drop_table('fingerprint')
    op.drop_index(op.f('ix_api_key_account_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_activation_key_tg_user_id'), table_name='activation_key')
    op.drop_index(op.f('ix_activation_key_redeemed_by_account_id'), table_name='activation_key')
    op.drop_table('activation_key')
    op.drop_table('server')
    op.drop_table('admin')
    op.drop_index('uq_account_login_active', table_name='account', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_account_expires_at', table_name='account')
    op.drop_table('account')
    op.drop_table('structure_class')
    op.drop_table('species')
    op.drop_table('person')
    op.drop_table('log_event_type')
    op.drop_table('invite_status')
    op.drop_table('group_role')
    op.drop_table('game_map')
    op.drop_table('component_type')
    op.drop_table('cluster')
    op.drop_table('api_key_status')
    op.drop_table('admin_status')
    op.drop_table('admin_role')
    op.drop_table('activation_key_status')
    op.drop_table('activation_key_origin')
    op.drop_table('account_status')
    # ### end Alembic commands ###
