"""account lockout columns and password reset tokens

Revision ID: d8b99f74a235
Revises: 93868d516e83
Create Date: 2026-08-30 21:49:35.525070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b99f74a235'
down_revision: Union[str, Sequence[str], None] = '93868d516e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_password_reset_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='SHA-256, НЕ argon2'),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=False, comment='кто выпустил — обязательный аудит'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='короткий TTL — не бессрочная замена паролю'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='NULL = ещё не погашен; погашается ровно 1 раз'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_account_password_reset_token_account_id'), 'account_password_reset_token', ['account_id'], unique=False)
    op.add_column('account', sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('account', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'locked_until')
    op.drop_column('account', 'failed_attempts')
    op.drop_index(op.f('ix_account_password_reset_token_account_id'), table_name='account_password_reset_token')
    op.drop_table('account_password_reset_token')
    # ### end Alembic commands ###
